ALTER TABLE "Product" DROP CONSTRAINT IF EXISTS "Product_fk0";
ALTER TABLE "SalesPerson" DROP CONSTRAINT IF EXISTS "SalesPerson_fk0";
ALTER TABLE "ProductReview" DROP CONSTRAINT IF EXISTS "ProductReview_fk0";
ALTER TABLE "ProductModelProductDescriptionCulture" DROP CONSTRAINT IF EXISTS "ProductModelProductDescriptionCulture_fk0";
ALTER TABLE "ProductSubCategory" DROP CONSTRAINT IF EXISTS "ProductSubCategory_fk0";
ALTER TABLE "SalesOrderHeader" DROP CONSTRAINT IF EXISTS "SalesOrderHeader_fk0";
ALTER TABLE "SalesOrderHeader" DROP CONSTRAINT IF EXISTS "SalesOrderHeader_fk1";
ALTER TABLE "SalesOrderDetail" DROP CONSTRAINT IF EXISTS "SalesOrderDetail_fk0";
ALTER TABLE "SalesOrderDetail" DROP CONSTRAINT IF EXISTS "SalesOrderDetail_fk1";
DROP TABLE IF EXISTS "Product";
DROP TABLE IF EXISTS "SalesPerson";
DROP TABLE IF EXISTS "ProductReview";
DROP TABLE IF EXISTS "ProductModelProductDescriptionCulture";
DROP TABLE IF EXISTS "ProductDescription";
DROP TABLE IF EXISTS "ProductCategory";
DROP TABLE IF EXISTS "ProductSubCategory";
DROP TABLE IF EXISTS "SalesOrderHeader";
DROP TABLE IF EXISTS "SalesOrderDetail";
DROP TABLE IF EXISTS "SalesTerritory";
DROP TABLE IF EXISTS "CountryRegionCurrency";
DROP TABLE IF EXISTS "CurrencyRate";
