CREATE TABLE "Product" (
	"ProductID" int,
	"Name" character varying(50),
	"ProductNumber" character varying(25),
	"MakeFlag" char(5),
	"FinishedGoodsFlag" char(5),
	"Color" character varying(15),
	"SafetyStockLevel" smallint,
	"ReorderPoint" smallint,
	"StandardCost" money,
	"ListPrice" money,
	"Size" character varying(5),
	"SizeUnitMeasureCode" char(3),
	"WeightUnitMeasureCode" char(3),
	"Weight" TEXT,
	"DaysToManufacture" int,
	"ProductLine" char(2),
	"Class" char(2),
	"Style" char(2),
	"ProductSubcategoryID" TEXT,
	"ProductModelID" TEXT,
	"SellStartDate" DATE,
	"SellEndDate" DATE,
	"DiscontinuedDate" DATE,
	"rowguid" uuid,
	"ModifiedDate" DATE
);